spring:
  application:
    name: USERSERVICE

  datasource:
    url: jdbc:postgresql://ep-twilight-pine-a1g5a9gi-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
    username: neondb_owner
    password: ${USER_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost
    ip-address: 127.0.0.1
    instance-id: localhost:8081

server:
  port: 8081